### ISSUE TITLE
srcset

### ISSUE THREAD

**Issue by farissi** [scratchoo/imagesStatus#1]
The <img> isn't detected when using srset on the image.

**Comment by scratchoo** [comment]
@farissi what's the part that isn't working ? I've tried an image with srcset and it's working for me, if you can provide a jsfiddle example that would be great.

**Comment by farissi** [comment]
I didn't manage to reproduce it on jsfiddle: https://jsfiddle.net/Farissi/e5yawsak/1/
However, the issue is happening once every 3 or 4 page refresh, the image is cached, and all the srcset image have same dimensions.
I will keep you updated if I manage to find what's causing this.
Many thanks!

**Comment by scratchoo** [comment]
@farissi I am not sure this will solve the issue but here is a new branch I just created trying to solve this : https://raw.githubusercontent.com/medBouzid/imagesStatus/1.1/imagesStatus.js
please use this and see if the problem still occur

**Comment by farissi** [comment]
@medBouzid, doesn't work either with the new code, I will try to investigate further on the issue and post an update once I find what was causing it.

Thank you for your investment.
